### ISSUE TITLE
Exchanges marketplace not loading

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#846] opened 2019-03-06 13:58 UTC
Exchanges marketplace listing is not working anymore, only the title is loading. Not sure if it's related, but the network console shows failed to load service-worker.js

https://gyazo.com/db35279c4b15d710728c9ff6c91acd4e

**Comment by rodrigopavezi** [comment] 2019-03-07 09:43
@oanamangiurea still see the issue so we need to try to replicate and fix it. cheers

**Comment by sk91** [comment] 2019-03-14 13:08
@oanamangiurea @rodrigopavezi, any pointers on how to replicate? works for me both for dist and dev

**Comment by sk91** [comment] 2019-03-14 13:16
Cannot reproduce, closing.

Will implement better exchanges loading as part of https://github.com/SelfKeyFoundation/Identity-Wallet/issues/571

**Closed by sk91** 2019-03-14 13:16 UTC
Labels: Bug
