### ISSUE TITLE
'Authentication Error with Trezor' is shown to first time users after clicking Start Incorporation even if user unlock wallet via Private Key or Keystore

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#785] opened 2019-03-02 17:55 UTC
Steps to replicate:
1. Unlock wallet via Private Key or Keystore File
2. Create SelfKey ID
3. Go to Incorporation Marketplace
4. Open an Incorporation
5. Click Start Incorporation
6. Click Start Incorporation second button
7. Check screen

Expected Result:
Checklist screen is shown

Actual Result:
'Authentication Error with Trezor' is displayed

http://recordit.co/ba698jdidL

**Comment by rhdelima** [comment] 2019-03-06 03:43
Failing this one. Still encountered the issue

**Comment by rodrigopavezi** [comment] 2019-03-06 10:09
@rhdelima if there is an communication issue with the KYC API it will show a error screen but it should not be related to Trezor anymore. Can you check it again that it is a different screen? cheers

**Comment by rhdelima** [comment] 2019-03-06 10:22
@rodrigopavezi The issue is encountered on WIN build only. I can show you later on the call

**Comment by rodrigopavezi** [comment] 2019-03-06 11:10
@rhdelima can you try again and please past here a screenshot. If it is the right screen I think we can close this issue. Cheers

**Comment by rhdelima** [comment] 2019-03-06 12:46
@rodrigopavezi Please see recording below. This is always encountered if you follow the steps on the recording.

http://recordit.co/bIYQkO8yMQ

**Comment by rhdelima** [comment] 2019-03-07 07:10
Still seeing the error always on WIN build.

**Comment by rhdelima** [comment] 2019-03-07 13:58
Issue is also now encountered using Trezor and Ledger.

http://recordit.co/HOXeUkDnQq
http://recordit.co/UYonNCRG7K

**Comment by eduardosmoura** [comment] 2019-03-07 21:43
@rodrigopavezi and @rhdelima I could replicate the issue on Windows 10: http://recordit.co/4aGOV2u6ej

Also, I noticed if we already have the Selfkey ID created the incorporation flow works properly: http://recordit.co/3jRc92WuHa

So, probably the issue is related to something missing to load during the transition from Selfkey ID creation and Incorporations loading...

**Comment by rodrigopavezi** [comment] 2019-03-08 19:28
@eduardosmoura I was trying to replicate and found the issue and also fixed it. Cheers

**Comment by eduardosmoura** [comment] 2019-03-08 22:08
@rodrigopavezi I tested your fix on Windows, and it's working correctly. @rhdelima could you test it again, please? Thank you guys.

**Closed** 2019-03-11 06:57 UTC
Labels: Bug, High Priority, QA-Failed, QA-Passed, QA-Ready
