### ISSUE TITLE
Attributes labels persistency

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#865] opened 2019-03-07 09:24 UTC
The following have happened on multiple profiles I have created. 

1. I created a selfkey id profile and filled all informations, giving each a different label
2. Switched to other profile and did the same, closed the wallet app over night 
3. When I open it again all the labels **from basic information** have been changed to https://gyazo.com/fa9ddbd7df3ed53c466f961276918a73 
4. The profile top part now also displays a [object Object] text https://gyazo.com/fdecd4f02978dd1de296bd133ffbfbf8

**Comment by rodrigopavezi** [comment] 2019-03-07 10:11
@oanamangiurea can you attach here the DB file?

**Comment by sk91** [comment] 2019-03-08 07:58
@oanamangiurea @rodrigopavezi cannot reproduce it.

- Tried simply closing the wallet and opening it after creating 2 profiles
- create 2 profiles in yesterday morning build  then run todays build against the same db

All works.

@oanamangiurea I don't know how it happened to you, but this label change shoudl be happening only when migrating from old wallet current release and current dev build

**Comment by rodrigopavezi** [comment] 2019-03-08 18:14
Will close it until we get more clear steps on how to reproduce it.

**Closed by rodrigopavezi** 2019-03-08 18:14 UTC
Labels: Bug, Can not Reproduce, High Priority

**Comment by andregoncalves** [comment] 2019-03-08 18:45
This also has happened to me before, but I can't reproduce it now.
Anyway, this could be a serious bug, we should be vigilant.
