### ISSUE TITLE
Wallet Identity migration causes mix-up in active selfkey-id

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1713] opened 2019-10-12 09:10 UTC
"I created a whole new wallet
Even though it is a new one, I see in the dashboard one of the coins that I added to my previous one (WAX)
Key appears double"

**Comment by andregoncalves** [comment] 2019-10-12 09:34
Might be related to #1712 and #1708

**Comment by sk91** [comment] 2019-10-14 14:01
duplicate of #1712

**Closed by sk91** 2019-10-14 14:01 UTC
Labels: Bug
